name:                groebner
version:             0.1.0.0
github:              "manzyuk/groebner"
license:             BSD3
author:              "Oleksandr Manzyuk"
maintainer:          "manzyuk@gmail.com"
copyright:           "2021 Oleksandr Manzyuk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A tiny EDSL for polynomial computations in Haskell
# category:            Computer Algebra

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/groebner#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- template-haskell

library:
  source-dirs: src

executables:
  groebner-examples:
    main:                Main.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - groebner
